version: '3.8'
services:
  db:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - ./database/1-schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./database/2-table.sql:/docker-entrypoint-initdb.d/2-table.sql
      - ./database/3-purchases.sql:/docker-entrypoint-initdb.d/3-purchases.sql
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local